name: 'onshape-action-summary'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: get-summary
      run: |
        echo "## Passed! \`${GITHUB_REF_NAME}\`" >> $GITHUB_STEP_SUMMARY
        echo "(${GITHUB_SHA})" >> $GITHUB_STEP_SUMMARY
      shell: bash
      env:
        GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
