name: 'onshape-action-summary'

runs:
  using: "composite"
  steps:
    - name: get-summary
      shell: bash
      run: |
        echo ${GITHUB_WORKSPACE}
        bash onshape/onshape-action-summary/action-summary.bash
      env:
        INPUT_STRING: "Hello there"
        GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
