name: 'onshape-action-summary'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: get-summary
      run: |
        set +x
        bash ${{ github.action_path }}/action-summary.bash >> $GITHUB_STEP_SUMMARY
      shell: bash
