name: 'onshape-action-summary'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: get-summary
      run: |
        pwd
        ls
        ls ..
        chmod +x ./action-summary.bash
        ./action-summary.bash
      shell: bash
      env:
        INPUT_STRING: "Hello there"
        GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
