name: 'onshape-action-summary'

runs:
  using: "composite"
  steps:
    - name: get-summary
      shell: bash
      run: |
        bash /home/runner/work/onshape-action-summary/onshape-action-summary/action-summary.bash
      env:
        INPUT_STRING: "Hello there"
        GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY
