name: 'test-action-summary'

inputs:
  do-fail:
    description: Simuate failed "build"
    type: boolean
    default: false

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run-test
        run: |
          echo "Running..."
          if $do-fail
          then
            echo "Failing!"
            exit 1
          else
            echo "Passing!"
            exit 0
        env:
          do-fail: inputs.do-fail
      - uses: onshape/onshape-action-summary@erousseau-build-actions
