name: 'test-action-summary'

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run-test
        run: |
          echo "Running..."
      - uses: onshape/onshape-action-summary@erousseau-build-actions
