name: 'test-action-summary'


on:
  workflow_dispatch:
    inputs:
      changeset:
        default: false
        type: boolean
      text:
        default: ""
        type: string

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          echo "Running..."
      - uses: onshape/onshape-action-summary@erousseau-build-actions
        env:
            CHANGESET: ${{ github.event.inputs.changeset }}
            TEXT: ${{ github.event.inputs.text }}
