name: 'test-action-summary'
description: 'Test summary wf'

jobs:
  run-test:
    steps:
      - name: test-summary
      - uses: onshape/onshape-action-summary@main
        shell: bash
        run: |
          echo "Running..."
