name: 'test-action-summary'



on:
  workflow_dispatch:
    inputs:
      dofail:
        description: Simuate failed "build"
        type: boolean
        default: false

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: run-test
        run: |
          set +x
          echo "Running..."
          echo "Do fail: ${dofail}"
          if $dofail
          then
            echo "Failing!"
            exit 1
          else
            echo "Passing!"
            exit 0
          fi
          exit 0
        env:
          dofail: ${{ inputs.dofail }}
      - uses: onshape/onshape-action-summary@erousseau-build-actions
        if: always()
