name: 'test-action-summary'
description: 'Test summary wf'

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
    - name: test-summary
      uses: onshape/onshape-action-summary@main
      run: |
        echo "Running..."
      shell: bash
